import Head from 'next/head';
import Header from '../components/header/header';
import Masthead from '../components/masthead/masthead';
import Footer from '../components/footer/footer';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<>
			<Head>
				<title>xo.systems</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<div className={styles.container}>
				<Masthead />
				<h1 className='text-columbia-300 font-bold text-2xl'> Hiwoo! </h1>
				<div className='half-screen'>
					<div className={styles.grid}>
						<div className={styles.card}>
							<h3>Hiwoo!</h3>
							<p> its wonderful! </p>
						</div>
					</div>
				</div>

				<Footer />
			</div>
		</>
	);
}
